name: Auto Send Email

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write  # Allow GITHUB_TOKEN to push commits

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository with push access
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run your email script
      - name: Run the script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python send_emails.py

      # 5. Commit & push updated CSV back to repo
      - name: Commit updated CSV
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hr_contacts.csv
          if ! git diff --cached --quiet; then
            git commit -m "Mark contact as sent [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
